from pathlib import Path
p=Path('outputs/surpresa/index.html')
s=p.read_text(encoding='utf-8-sig')
s=s.replace(".lyric-stage{min-height:90px;display:flex;align-items:center;justify-content:center;max-width:760px;margin:20px auto;padding:16px;color:#9f3853;font-family:'Palatino Linotype','Book Antiqua',Georgia,serif;font-size:clamp(1.35rem,3.5vw,2.15rem);font-style:italic;line-height:1.28;text-wrap:balance;text-shadow:0 5px 22px #b84c6820;opacity:0;transform:translateY(12px);transition:opacity .6s,transform .6s}.lyric-stage.visible{opacity:1;transform:translateY(0)}.lyric-stage .glyph{display:inline-block;animation:glyph-in .48s both;animation-delay:calc(var(--glyph-index)*16ms)}", ".lyric-stage{display:block;width:100%;max-width:100%;min-width:0;min-height:84px;box-sizing:border-box;margin:18px auto;padding:14px 10px;color:#9f3853;font-family:'Palatino Linotype','Book Antiqua',Georgia,serif;font-size:clamp(1.25rem,3.5vw,2.05rem);font-style:italic;line-height:1.35;text-align:center;text-wrap:balance;overflow-wrap:break-word;word-break:normal;text-shadow:0 5px 22px #b84c6820;opacity:0;transform:translateY(12px);transition:opacity .6s,transform .6s}.lyric-stage.visible{opacity:1;transform:translateY(0)}.lyric-stage .glyph{display:inline-block;white-space:nowrap;animation:glyph-in .48s both;animation-delay:calc(var(--glyph-index)*70ms)}")
s=s.replace("@media(max-width:700px){.memory-layout{grid-template-columns:1fr;text-align:center}.photo-main{max-height:65vh}.memory-layout .actions{justify-content:center}.gallery img{height:210px}.unit{min-width:60px;padding:12px 7px}}", "@media(max-width:700px){.card{padding:26px 20px;border-radius:22px}.memory-layout{grid-template-columns:minmax(0,1fr);gap:20px;text-align:center}.photo-main{max-height:54vh;max-width:100%}.letter{font-size:1rem;line-height:1.72;text-align:left}.lyric-stage{min-height:76px;padding:12px 4px;margin:12px auto;font-size:clamp(1.12rem,5.2vw,1.42rem);line-height:1.38}.memory-layout .actions{justify-content:center}.gallery{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.gallery img{height:clamp(155px,52vw,220px)}.caption{font-size:1.08rem;line-height:1.6}.timer{gap:7px}.unit{min-width:0;flex:1;padding:12px 5px}.unit span{font-size:.62rem}}")
old="function writeLyric(stage,line){stage.replaceChildren();stage.setAttribute('aria-label',line);Array.from(line).forEach((char,i)=>{const span=document.createElement('span');span.className='glyph';span.style.setProperty('--glyph-index',i);span.textContent=char===' '?'\\u00a0':char;stage.appendChild(span)});stage.classList.add('visible')}\n    let lastLine1=-1,lastLine3=-1,lastPhotoCount=0,lastBeat=-1;\n    audios[0].addEventListener('timeupdate',()=>{const n=Math.floor(Math.max(0,audios[0].currentTime-39)/5);if(n!==lastLine1){lastLine1=n;writeLyric(document.getElementById('lyric1'),lines1[n%lines1.length])}});\n    audios[1].addEventListener('timeupdate',()=>{const elapsed=Math.max(0,audios[1].currentTime-51),beat=Math.floor(elapsed/.62),n=Math.floor(elapsed/7);if(n!==lastLine3){lastLine3=n;writeLyric(document.getElementById('lyric3'),lines3[n%lines3.length])}const imgs=gallery.querySelectorAll('img'),count=Math.min(imgs.length,Math.floor(elapsed/1.25)+1);while(lastPhotoCount<count)imgs[lastPhotoCount++].classList.add('is-visible');if(beat!==lastBeat){lastBeat=beat;gallery.classList.toggle('beat',beat%2===0)}});"
new="function writeLyric(stage,line){stage.replaceChildren();stage.setAttribute('aria-label',line);const words=line.split(/\\s+/);words.forEach((word,i)=>{const span=document.createElement('span');span.className='glyph';span.style.setProperty('--glyph-index',i);span.textContent=word;stage.appendChild(span);if(i<words.length-1)stage.appendChild(document.createTextNode(' '))});stage.classList.add('visible')}\n    const cues1=[42.04,46.45,50.67,54.85,58.87,63.30,67.50,71.70,151.72,153.86,156.00,158.03,160.35,162.25,164.35,166.47,169.14,173.87,177.93,182.22,185.40,188.88,193.79,198.02];\n    const cues3=[51,54,58,63,66,70,97,101,108,110,115,121,124,129,132,136,140,145,148,152];\n    let lastLine1=-1,lastLine3=-1,lastPhotoCount=0,lastBeat=-1;\n    function cueIndex(time,cues){let i=-1;for(let n=0;n<cues.length;n++){if(time>=cues[n])i=n;else break}return i}\n    function syncLyric(audio,stage,lines,cues,last){const n=cueIndex(audio.currentTime,cues);if(n<0){stage.classList.remove('visible');return last}if(n!==last){writeLyric(stage,lines[n]);last=n}const until=cues[n+1]??(cues[n]+5);if(audio.currentTime>Math.min(until,cues[n]+5))stage.classList.remove('visible');return last}\n    audios[0].addEventListener('timeupdate',()=>{lastLine1=syncLyric(audios[0],document.getElementById('lyric1'),lines1,cues1,lastLine1)});\n    audios[1].addEventListener('timeupdate',()=>{lastLine3=syncLyric(audios[1],document.getElementById('lyric3'),lines3,cues3,lastLine3);const elapsed=Math.max(0,audios[1].currentTime-51),beat=Math.floor(elapsed/.62),imgs=gallery.querySelectorAll('img'),count=Math.min(imgs.length,Math.floor(elapsed/1.25)+1);while(lastPhotoCount<count)imgs[lastPhotoCount++].classList.add('is-visible');if(beat!==lastBeat){lastBeat=beat;gallery.classList.toggle('beat',beat%2===0)}});"
if old not in s:
    raise SystemExit('JS lyric block was not found; no JS changes made')
s=s.replace(old,new)
s=s.replace("2026-11-21T21:00:00-03:00","2026-12-06T21:00:00-03:00")
s=s.replace("21h de 21/11/2026","21h de 06/12/2026")
p.write_text(s,encoding='utf-8')
